services:
  - type: web
    name: bookstore
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: "gunicorn bookstore.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: bookstore.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: CLOUDINARY_CLOUD_NAME
        value: book
      - key: CLOUDINARY_API_KEY
        value: 288666812355435
      - key: CLOUDINARY_API_SECRET
        value: Buf6_C4zsSMUzl9s4pvJhaVWJDI